//------------------------------------------------------------------------------
// <auto-generated>
//    Codice generato da un modello.
//
//    Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//    Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Novus_Daedalus.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class atto
    {
        public atto()
        {
            this.AttoCosa = new HashSet<AttoCosa>();
            this.PersonaAtto = new HashSet<PersonaAtto>();
            this.ReatoAtto = new HashSet<ReatoAtto>();
        }
    
        public int Id { get; set; }
        public string Scopo { get; set; }
        public string Tipo { get; set; }
        public string Nome { get; set; }
        public Nullable<System.DateTime> DataEsecuzione { get; set; }
        public string Stato { get; set; }
        public string Esito { get; set; }
        public Nullable<int> IdScheda { get; set; }
    
        public virtual ICollection<AttoCosa> AttoCosa { get; set; }
        public virtual ICollection<PersonaAtto> PersonaAtto { get; set; }
        public virtual ICollection<ReatoAtto> ReatoAtto { get; set; }
        public virtual scheda scheda { get; set; }
    }
}
