//------------------------------------------------------------------------------
// <auto-generated>
//    Codice generato da un modello.
//
//    Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//    Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Novus_Daedalus.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class atto
    {
        public atto()
        {
            this.atto_cosa = new HashSet<atto_cosa>();
            this.persona_atto = new HashSet<persona_atto>();
            this.reato_atto = new HashSet<reato_atto>();
        }
    
        public int Id { get; set; }
        public string Scopo { get; set; }
        public string Tipo { get; set; }
        public string Nome { get; set; }
        public string DataEsecuzione { get; set; }
        public string Stato { get; set; }
        public string Esito { get; set; }
        public Nullable<int> IdScheda { get; set; }
    
        public virtual ICollection<atto_cosa> atto_cosa { get; set; }
        public virtual ICollection<persona_atto> persona_atto { get; set; }
        public virtual ICollection<reato_atto> reato_atto { get; set; }
        public virtual scheda scheda { get; set; }
    }
}
