//------------------------------------------------------------------------------
// <auto-generated>
//    Codice generato da un modello.
//
//    Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//    Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Novus_Daedalus.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class collaboratore
    {
        public int Id { get; set; }
    
        public virtual persona persona { get; set; }
        public virtual consulente consulente { get; set; }
        public virtual interprete interprete { get; set; }
        public virtual pg pg { get; set; }
    }
}
