//------------------------------------------------------------------------------
// <auto-generated>
//    Codice generato da un modello.
//
//    Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//    Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Novus_Daedalus.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class cosa
    {
        public cosa()
        {
            this.atto_cosa = new HashSet<atto_cosa>();
            this.persona_cosa = new HashSet<persona_cosa>();
            this.reato_cosa = new HashSet<reato_cosa>();
        }
    
        public int Id { get; set; }
        public string Qualità { get; set; }
        public string Origine { get; set; }
        public string Acquisizione { get; set; }
        public string Descrizione { get; set; }
        public string Evento { get; set; }
        public string AttoOrigine { get; set; }
        public Nullable<int> IdScheda { get; set; }
    
        public virtual ICollection<atto_cosa> atto_cosa { get; set; }
        public virtual ICollection<persona_cosa> persona_cosa { get; set; }
        public virtual ICollection<reato_cosa> reato_cosa { get; set; }
        public virtual scheda scheda { get; set; }
    }
}
