//------------------------------------------------------------------------------
// <auto-generated>
//    Codice generato da un modello.
//
//    Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//    Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Novus_Daedalus.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class difensore
    {
        public difensore()
        {
            this.indagato = new HashSet<indagato>();
            this.indagato1 = new HashSet<indagato>();
        }
    
        public int Id { get; set; }
        public string Qualità { get; set; }
    
        public virtual persona persona { get; set; }
        public virtual ICollection<indagato> indagato { get; set; }
        public virtual ICollection<indagato> indagato1 { get; set; }
    }
}
