//------------------------------------------------------------------------------
// <auto-generated>
//    Codice generato da un modello.
//
//    Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//    Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Novus_Daedalus.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class indagato
    {
        public indagato()
        {
            this.Iscrive = new HashSet<Iscrive>();
        }
    
        public int Id { get; set; }
        public string Stato { get; set; }
        public string PrecedentiPenali { get; set; }
        public string QualitàDifesa { get; set; }
        public Nullable<int> Difensore1 { get; set; }
        public Nullable<int> Difensore2 { get; set; }
        public Nullable<System.DateTime> InizioMisuraCautelare { get; set; }
    
        public virtual difensore difensore { get; set; }
        public virtual difensore difensore3 { get; set; }
        public virtual persona persona { get; set; }
        public virtual ICollection<Iscrive> Iscrive { get; set; }
    }
}
