//------------------------------------------------------------------------------
// <auto-generated>
//    Codice generato da un modello.
//
//    Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//    Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Novus_Daedalus.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class iscrizione
    {
        public iscrizione()
        {
            this.Iscrive = new HashSet<Iscrive>();
            this.scheda = new HashSet<scheda>();
        }
    
        public int Id { get; set; }
        public string Ufficio { get; set; }
        public string Sede { get; set; }
        public string Referente { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
        public Nullable<System.DateTime> DataScadenza { get; set; }
        public string Stato { get; set; }
        public string ArchiviazioneImmediata { get; set; }
        public string Memo { get; set; }
        public string IndaginiPG { get; set; }
    
        public virtual ICollection<Iscrive> Iscrive { get; set; }
        public virtual ICollection<scheda> scheda { get; set; }
    }
}
