//------------------------------------------------------------------------------
// <auto-generated>
//    Codice generato da un modello.
//
//    Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//    Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Novus_Daedalus.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class polizia_giudiziaria
    {
        public string CodiceFiscale { get; set; }
        public string Nome { get; set; }
        public string Sede { get; set; }
        public string Funzione { get; set; }
        public string Grado { get; set; }
    
        public virtual collaboratore collaboratore { get; set; }
    }
}
