//------------------------------------------------------------------------------
// <auto-generated>
//    Codice generato da un modello.
//
//    Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//    Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Novus_Daedalus.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReatoAtto
    {
        public int IdReato { get; set; }
        public int IdAtto { get; set; }
        public Nullable<int> IdScheda { get; set; }
    
        public virtual atto atto { get; set; }
        public virtual reato reato { get; set; }
        public virtual scheda scheda { get; set; }
    }
}
