//------------------------------------------------------------------------------
// <auto-generated>
//    Codice generato da un modello.
//
//    Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//    Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Novus_Daedalus.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class reato
    {
        public reato()
        {
            this.iscrizione = new HashSet<iscrizione>();
            this.scheda = new HashSet<scheda>();
        }
    
        public int Id { get; set; }
        public string Codice { get; set; }
        public string NomenIuris { get; set; }
        public string Luogo { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
    
        public virtual ICollection<iscrizione> iscrizione { get; set; }
        public virtual ICollection<scheda> scheda { get; set; }
    }
}
