//------------------------------------------------------------------------------
// <auto-generated>
//    Codice generato da un modello.
//
//    Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//    Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Novus_Daedalus.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class reato
    {
        public reato()
        {
            this.iscrizione = new HashSet<iscrizione>();
            this.persona_reato = new HashSet<persona_reato>();
            this.reato_atto = new HashSet<reato_atto>();
            this.reato_cosa = new HashSet<reato_cosa>();
        }
    
        public int Id { get; set; }
        public string Codice { get; set; }
        public string NomenIuris { get; set; }
        public string Luogo { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
        public Nullable<int> IdScheda { get; set; }
    
        public virtual ICollection<iscrizione> iscrizione { get; set; }
        public virtual ICollection<persona_reato> persona_reato { get; set; }
        public virtual ICollection<reato_atto> reato_atto { get; set; }
        public virtual ICollection<reato_cosa> reato_cosa { get; set; }
        public virtual scheda scheda { get; set; }
    }
}
