//------------------------------------------------------------------------------
// <auto-generated>
//    Codice generato da un modello.
//
//    Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//    Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Novus_Daedalus.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class reato
    {
        public reato()
        {
            this.iscrizione = new HashSet<iscrizione>();
            this.persona = new HashSet<persona>();
            this.atto = new HashSet<atto>();
            this.cosa = new HashSet<cosa>();
        }
    
        public int Id { get; set; }
        public string Codice { get; set; }
        public string NomenIuris { get; set; }
        public string Luogo { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
        public Nullable<int> IdScheda { get; set; }
    
        public virtual ICollection<iscrizione> iscrizione { get; set; }
        public virtual scheda scheda { get; set; }
        public virtual ICollection<persona> persona { get; set; }
        public virtual ICollection<atto> atto { get; set; }
        public virtual ICollection<cosa> cosa { get; set; }
    }
}
