//------------------------------------------------------------------------------
// <auto-generated>
//    Codice generato da un modello.
//
//    Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//    Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Novus_Daedalus.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class scheda
    {
        public int Id { get; set; }
        public int IdRegistro { get; set; }
        public string CodiceFiscalePersona { get; set; }
        public int IdReato { get; set; }
        public int IdAtto { get; set; }
        public int IdCosa { get; set; }
    
        public virtual atto atto { get; set; }
        public virtual cosa cosa { get; set; }
        public virtual persona persona { get; set; }
        public virtual reato reato { get; set; }
    }
}
