//------------------------------------------------------------------------------
// <auto-generated>
//    Codice generato da un modello.
//
//    Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//    Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Novus_Daedalus.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class scheda
    {
        public scheda()
        {
            this.atto = new HashSet<atto>();
            this.cosa = new HashSet<cosa>();
            this.reato = new HashSet<reato>();
            this.persona = new HashSet<persona>();
        }
    
        public int Id { get; set; }
        public Nullable<int> NumeroRegistro { get; set; }
        public Nullable<System.DateTime> DataRegistrazione { get; set; }
    
        public virtual ICollection<atto> atto { get; set; }
        public virtual ICollection<cosa> cosa { get; set; }
        public virtual ICollection<reato> reato { get; set; }
        public virtual ICollection<persona> persona { get; set; }
    }
}
